language: node_js

cache: yarn

notifications:
  email: false

node_js:
  - "8"
  - "10"

install:
  - yarn

before_script:
  - yarn ci

script:
  - yarn build

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

jobs:
  include:
    - stage: publish to codecov
      node_js: "8"
      script: yarn codecov

    - stage: publish npm
      node_js: "8"
      deploy:
        provider: npm
        skip_cleanup: true
        email: uma.karimov@gmail.com
        api_key: $NPM_TOKEN
        on:
          tags: true
          branch: master
          repo: dcodeteam/react-google-maps

    - stage: deploy pages
      node_js: "8"
      deploy:
        provider: pages
        local-dir: ./docs
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        on:
          tags: true
          branch: master
          repo: dcodeteam/react-google-maps
